import express from 'express';
import crypto from 'node:crypto';
import { db } from './db.js';

const app = express();
const PORT = Number(process.env.API_PORT || 8787);
app.use(express.json({ limit: '1mb' }));
const id = p => `${p}_${crypto.randomUUID()}`;
const hash = password => crypto.scryptSync(password, process.env.VIYRO_PASSWORD_SALT || 'change-this-salt-before-production', 64).toString('hex');
const publicUser = u => ({ id:u.id, name:u.name, email:u.email, phone:u.phone });
function getBusiness(user) { return db.prepare('SELECT * FROM businesses WHERE owner_id = ? ORDER BY created_at LIMIT 1').get(user.id); }
function auth(req,res,next){ const userId=req.header('x-user-id'); if(!userId)return res.status(401).json({error:'Authentication required.'}); const user=db.prepare('SELECT * FROM users WHERE id=?').get(userId); if(!user)return res.status(401).json({error:'Invalid session.'}); req.user=user; req.business=getBusiness(user); next(); }
function audit(req,action,entity,entityId){ db.prepare('INSERT INTO audit_logs (user_id,business_id,action,entity,entity_id) VALUES (?,?,?,?,?)').run(req.user.id,req.business?.id||null,action,entity,entityId||null); }
app.get('/api/health',(_req,res)=>res.json({ok:true,database:'sqlite',service:'viyro-api'}));
app.post('/api/auth/signup',(req,res)=>{ const {name,email,phone,password}=req.body||{}; if(!name?.trim()||!email?.trim()||!password||password.length<8)return res.status(400).json({error:'Name, email and an 8+ character password are required.'}); const normalized=email.trim().toLowerCase(); if(db.prepare('SELECT id FROM users WHERE email=?').get(normalized))return res.status(409).json({error:'An account with this email already exists.'}); const userId=id('usr'),businessId=id('biz'); db.transaction(()=>{db.prepare('INSERT INTO users(id,name,email,phone,password_hash) VALUES(?,?,?,?,?)').run(userId,name.trim(),normalized,phone?.trim()||null,hash(password));db.prepare('INSERT INTO businesses(id,owner_id,name) VALUES(?,?,?)').run(businessId,userId,`${name.trim()}'s workspace`);db.prepare('INSERT INTO audit_logs(user_id,business_id,action,entity,entity_id) VALUES(?,?,?,?,?)').run(userId,businessId,'account_created','user',userId);})(); res.status(201).json({user:{id:userId,name:name.trim(),email:normalized,phone:phone?.trim()||''},businessId}); });
app.post('/api/auth/login',(req,res)=>{ const {email,password}=req.body||{}; const user=db.prepare('SELECT * FROM users WHERE email=?').get(email?.trim().toLowerCase()); if(!user||!user.password_hash)return res.status(401).json({error:'Those sign-in details do not match.'}); const a=Buffer.from(user.password_hash,'hex'),b=Buffer.from(hash(password||''),'hex'); if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Those sign-in details do not match.'}); const biz=getBusiness(user); db.prepare('INSERT INTO audit_logs(user_id,business_id,action,entity,entity_id) VALUES(?,?,?,?,?)').run(user.id,biz?.id||null,'login','user',user.id); res.json({user:publicUser(user),businessId:biz?.id}); });
app.get('/api/workspace',auth,(req,res)=>{ const b=req.business; if(!b)return res.status(404).json({error:'Workspace not found.'}); const all=t=>db.prepare(`SELECT * FROM ${t} WHERE business_id=? ORDER BY created_at DESC`).all(b.id); res.json({user:publicUser(req.user),business:b,transactions:all('transactions'),customers:all('customers'),products:all('products'),invoices:all('invoices'),notifications:all('notifications').filter(x=>!x.read)}); });
const routes={transactions:{fields:['type','description','amount','category'],sql:'INSERT INTO transactions(id,business_id,type,description,amount,category) VALUES(?,?,?,?,?,?)'},customers:{fields:['name','email','phone','notes'],sql:'INSERT INTO customers(id,business_id,name,email,phone,notes) VALUES(?,?,?,?,?,?)'},products:{fields:['name','type','price','description'],sql:'INSERT INTO products(id,business_id,name,type,price,description) VALUES(?,?,?,?,?,?)'},invoices:{fields:['invoice_number','amount','status','due_date','notes'],sql:'INSERT INTO invoices(id,business_id,invoice_number,amount,status,due_date,notes) VALUES(?,?,?,?,?,?,?)'}};
for(const [name,cfg] of Object.entries(routes)){app.post(`/api/${name}`,auth,(req,res)=>{const vals=cfg.fields.map(f=>req.body?.[f]??null);if(name==='transactions'&&(!vals[1]||Number(vals[2])<0))return res.status(400).json({error:'Description and a valid amount are required.'});if(name==='customers'&&!vals[0]?.trim())return res.status(400).json({error:'Customer name is required.'});if(name==='products'&&(!vals[0]?.trim()||Number(vals[2])<0))return res.status(400).json({error:'Product name and a valid price are required.'});if(name==='invoices'&&(!vals[0]?.trim()||Number(vals[1])<0))return res.status(400).json({error:'Invoice number and a valid amount are required.'});try{const recordId=id(name.slice(0,3));db.prepare(cfg.sql).run(recordId,req.business.id,...vals);audit(req,`${name.slice(0,-1)}_created`,name.slice(0,-1),recordId);res.status(201).json(db.prepare(`SELECT * FROM ${name} WHERE id=?`).get(recordId));}catch(e){res.status(400).json({error:e.message});}});app.delete(`/api/${name}/:id`,auth,(req,res)=>{const result=db.prepare(`DELETE FROM ${name} WHERE id=? AND business_id=?`).run(req.params.id,req.business.id);if(!result.changes)return res.status(404).json({error:'Record not found.'});audit(req,`${name.slice(0,-1)}_deleted`,name.slice(0,-1),req.params.id);res.status(204).end();});}
app.patch('/api/notifications/:id/read',auth,(req,res)=>{db.prepare('UPDATE notifications SET read=1 WHERE id=? AND business_id=?').run(req.params.id,req.business.id);res.status(204).end();});
app.listen(PORT,'0.0.0.0',()=>console.log(`Viyro API running on http://localhost:${PORT}`));
