import { useEffect, useMemo, useState } from 'react';

const KEY = 'viyro_db_v2';
const AUTH = 'viyro_auth';
const blank = { transactions: [], customers: [], products: [], invoices: [], notifications: [] };
const nav = [
  ['overview','Overview','home'], ['transactions','Transactions','swap'], ['customers','Customers','users'],
  ['products','Products','box'], ['invoices','Invoices','file'], ['reports','Reports','chart'], ['notifications','Notifications','bell']
];

function read(key, fallback){ try{return JSON.parse(localStorage.getItem(key)) ?? fallback}catch{return fallback} }
function money(n){return new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(Number(n)||0)}
function id(prefix){return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function Icon({name,size=18}){
  const p={width:size,height:size,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:'1.8',strokeLinecap:'round',strokeLinejoin:'round'};
  const paths={home:<><path d="m3 10 9-7 9 7"/><path d="M5 9v11h14V9"/><path d="M9 20v-6h6v6"/></>,swap:<><path d="M7 7h11l-3-3"/><path d="M17 17H6l3 3"/><path d="M18 4v3M6 17v3"/></>,users:<><path d="M16 20v-1.5a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4V20"/><circle cx="9.5" cy="7.5" r="3.5"/><path d="M17 11a3 3 0 1 0-1-5.8M21 20v-1.2a4 4 0 0 0-2.8-3.8"/></>,box:<><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3Z"/><path d="m4.5 7.5 7.5 4 7.5-4M12 12v9"/></>,file:<><path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5M9 13h6M9 17h6"/></>,chart:<><path d="M4 19V5M4 19h17"/><path d="m7 15 4-5 3 3 5-7"/></>,bell:<><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></>,plus:<path d="M12 5v14M5 12h14"/>,search:<><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></>,sun:<><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></>,moon:<path d="M20.5 15.5A8.5 8.5 0 0 1 8.5 3.5a8.6 8.6 0 1 0 12 12Z"/>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-2.6V20a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1A1.7 1.7 0 0 0 8 15a1.7 1.7 0 0 0-1.6-1H6v-2.6h.4A1.7 1.7 0 0 0 8 10a1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1A1.7 1.7 0 0 0 11.4 6a1.7 1.7 0 0 0 1-1.6V4H15v.4a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2V14H21a1.7 1.7 0 0 0-1.6 1Z"/></>};
  return <svg {...p}>{paths[name]}</svg>
}
function Logo({small=false}){return <div className={`logo ${small?'logo-small':''}`}><span className="logo-v">V</span><span className="logo-dot"/><span className="logo-name">Vero</span></div>}

function Loader({done}){useEffect(()=>{const t=setTimeout(done,7200);return()=>clearTimeout(t)},[done]);return <div className="v-loader"><div className="loader-light one"/><div className="loader-light two"/><div className="loader-stage"><div className="loader-v"><span/><span/><i/></div><div className="walker"><div className="person-head"/><div className="person-body"><b>V</b></div><div className="person-arm left"/><div className="person-arm right"/><div className="person-leg left"/><div className="person-leg right"/><div className="case"><em/><strong/></div></div></div><div className="loader-brand">Vero</div><div className="loader-tag">Business, made clearer.</div><div className="loader-progress"><span/></div></div>}

function Auth({onLogin}){const [signup,setSignup]=useState(false);const [f,setF]=useState({name:'',email:'',phone:'',password:''});const [err,setErr]=useState('');const [msg,setMsg]=useState('');
 const submit=e=>{e.preventDefault();setErr('');setMsg('');if(signup&&!f.name.trim())return setErr('Enter your name.');if(!f.email.includes('@'))return setErr('Enter a valid email.');if(f.password.length<8)return setErr('Use at least 8 characters for your password.');const old=read(AUTH,null);if(signup){localStorage.setItem(AUTH,JSON.stringify({name:f.name.trim(),email:f.email.trim().toLowerCase(),phone:f.phone.trim()}));setMsg('Account created on this device.');setSignup(false);setF({...f,password:''})}else{if(!old||old.email!==f.email.trim().toLowerCase())return setErr('No Vero account with that email was found on this device.');onLogin(old)}};
 return <div className="auth"><div className="auth-photo"><div className="photo-shade"/><div className="auth-message"><span>VERO / BUSINESS WORKSPACE</span><h1>Make decisions<br/>with a clearer view.</h1><p>Keep your money, customers, products and invoices in one calm workspace.</p></div></div><div className="auth-form-side"><div className="auth-box"><Logo/><div className="auth-title"><small>{signup?'NEW WORKSPACE':'PRIVATE WORKSPACE'}</small><h2>{signup?'Start with Vero.':'Welcome back.'}</h2><p>{signup?'Create your account and begin with a clean workspace.':'Sign in to your workspace and pick up where you left off.'}</p></div><form onSubmit={submit}>{signup&&<Field label="Name"><input name="name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} placeholder="Your name"/></Field>}<Field label="Email"><input name="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} placeholder="you@example.com"/></Field>{signup&&<Field label="Phone"><input name="phone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})} placeholder="07xx xxx xxx"/></Field>}<Field label="Password"><input type="password" name="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})} placeholder="At least 8 characters"/></Field>{err&&<div className="form-alert error">{err}</div>}{msg&&<div className="form-alert ok">{msg}</div>}<button className="btn-primary" type="submit">{signup?'Create account':'Sign in'}</button></form><div className="or"><span>or</span></div><button className="btn-secondary" type="button" onClick={()=>setErr('Google sign-in needs an OAuth client configured for this deployment.')}>Continue with Google</button><p className="switch">{signup?'Already have an account?':'New to Vero?'} <button onClick={()=>{setSignup(!signup);setErr('');setMsg('')}}>{signup?'Sign in':'Create account'}</button></p><small className="legal">Your workspace is private to your account. Terms and Privacy apply.</small></div></div></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}

function Shell({user,onLogout}){const [db,setDb]=useState(()=>({...blank,...read(KEY,blank)}));const [page,setPage]=useState('overview');const [modal,setModal]=useState(null);const [q,setQ]=useState('');const [theme,setTheme]=useState(()=>localStorage.getItem('viyro_theme')||'dark');const [toast,setToast]=useState('');
 useEffect(()=>localStorage.setItem(KEY,JSON.stringify(db)),[db]);useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('viyro_theme',theme)},[theme]);
 const income=db.transactions.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0), expenses=db.transactions.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0);const profit=income-expenses;const notify=x=>{setToast(x);setTimeout(()=>setToast(''),2600)};const add=(collection,data,label)=>{setDb(d=>({...d,[collection]:[...d[collection],{...data,id:id(collection.slice(0,3)),createdAt:Date.now()}]}));setModal(null);notify(label)};
 const search=useMemo(()=>{if(!q.trim())return[];const s=q.toLowerCase();return [...db.customers.map(x=>({type:'customers',name:x.name})),...db.products.map(x=>({type:'products',name:x.name})),...db.transactions.map(x=>({type:'transactions',name:x.description}))].filter(x=>x.name?.toLowerCase().includes(s)).slice(0,6)},[q,db]);
 const title={overview:'Overview',transactions:'Transactions',customers:'Customers',products:'Products',invoices:'Invoices',reports:'Reports',notifications:'Notifications',settings:'Settings'}[page];
 return <div className="app-shell"><aside className="side"><Logo/><div className="account"><div className="account-avatar">{user.name?.[0]?.toUpperCase()||'V'}</div><div><strong>{user.name||'My workspace'}</strong><small>{user.email}</small></div></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([id,label,icon])=><button key={id} className={page===id?'selected':''} onClick={()=>setPage(id)}><Icon name={icon}/><span>{label}</span>{id==='notifications'&&db.notifications.length>0&&<b>{db.notifications.length}</b>}</button>)}</nav><div className="side-bottom"><button className={page==='settings'?'selected':''} onClick={()=>setPage('settings')}><Icon name="settings"/><span>Settings</span></button><div className="privacy"><i/>Private workspace</div></div></aside><main className="main"><header className="header"><div className="mobile-logo"><Logo small/></div><div className="search"><Icon name="search" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers, products, transactions"/>{q&&<div className="results">{search.length?search.map((x,i)=><button key={i} onClick={()=>{setPage(x.type);setQ('')}}><small>{x.type}</small>{x.name}</button>):<p>No records found.</p>}</div>}</div><div className="header-actions"><button className="header-icon" onClick={()=>setTheme(theme==='dark'?'light':'dark')}><Icon name={theme==='dark'?'sun':'moon'} size={17}/></button><button className="header-icon" onClick={()=>setPage('notifications')}><Icon name="bell" size={17}/>{db.notifications.length>0&&<i/>}</button><button className="user-button" onClick={onLogout}>{user.name?.[0]?.toUpperCase()||'V'}</button></div></header><div className="page"><div className="page-top"><div><span className="section-label">{page==='overview'?'BUSINESS CONTROL':'VERO WORKSPACE'}</span><h1>{title}</h1><p>{page==='overview'?'A working view of the records you choose to keep.':'Manage the records in this workspace.'}</p></div>{page!=='reports'&&page!=='notifications'&&page!=='settings'&&<button className="btn-primary add" onClick={()=>setModal(page==='transactions'||page==='overview'?'transaction':page.slice(0,-1))}><Icon name="plus" size={16}/> {page==='transactions'||page==='overview'?'Record transaction':page==='customers'?'Add customer':page==='products'?'Add product':'Create invoice'}</button>}</div>{page==='overview'?<Overview db={db} income={income} expenses={expenses} profit={profit} go={setPage} open={setModal}/>:<Records page={page} db={db} remove={(c,id)=>{setDb(d=>({...d,[c]:d[c].filter(x=>x.id!==id)}));notify('Record removed')}} open={setModal}/>}</div>{toast&&<div className="toast">{toast}</div>}{modal&&<Modal type={modal} close={()=>setModal(null)} submit={(collection,data,label)=>add(collection,data,label)}/>}</main></div>}

function Overview({db,income,expenses,profit,go,open}){const tx=[...db.transactions].sort((a,b)=>b.createdAt-a.createdAt).slice(0,5);return <div className="overview"><div className="stats"><Stat label="Income" value={money(income)} note="Recorded"/><Stat label="Expenses" value={money(expenses)} note="Recorded"/><Stat label="Net position" value={money(profit)} note={profit>=0?'Positive':'Needs attention'}/><Stat label="Activity" value={db.transactions.length} note="Transactions"/></div><div className="overview-grid"><section className="section-card"><div className="card-title"><div><h2>Recent activity</h2><p>The latest records in your workspace.</p></div><button onClick={()=>go('transactions')}>View all</button></div>{tx.length?<div className="activity">{tx.map(x=><div className="activity-row" key={x.id}><div className={`activity-mark ${x.type}`}>{x.type==='income'?'+':'−'}</div><div><strong>{x.description}</strong><small>{new Date(x.createdAt).toLocaleDateString()}</small></div><strong className={x.type==='income'?'positive':'negative'}>{x.type==='income'?'+':'−'}{money(x.amount)}</strong></div>)}</div>:<Empty icon="swap" title="Your activity starts here" text="Record your first income or expense and Vero will begin building your picture." action={<button className="text-action" onClick={()=>open('transaction')}>Record first transaction →</button>}/>}</section><section className="section-card"><div className="card-title"><div><h2>Workspace status</h2><p>Nothing hidden, nothing simulated.</p></div></div><div className="status-list"><Status label="Transactions" value={db.transactions.length}/><Status label="Customers" value={db.customers.length}/><Status label="Products" value={db.products.length}/><Status label="Invoices" value={db.invoices.length}/></div><div className="insight"><span>V</span><div><strong>Vero insight</strong><p>{db.transactions.length?'Insights will become more useful as your real records grow.':'Add real records first. Vero will not invent business performance.'}</p></div></div></section></div></div>}
function Stat({label,value,note}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Status({label,value}){return <div className="status"><span>{label}</span><strong>{value}</strong></div>}
function Empty({icon,title,text,action}){return <div className="empty"><div className="empty-symbol"><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p>{action}</div>}

function Records({page,db,remove,open}){const map={transactions:{c:'transactions',title:'Transactions'},customers:{c:'customers',title:'Customers'},products:{c:'products',title:'Products'},invoices:{c:'invoices',title:'Invoices'},reports:null,notifications:null};if(page==='reports')return <Reports db={db}/>;if(page==='notifications')return <Notifications db={db}/>;const m=map[page];const items=db[m.c];if(!items.length)return <section className="records-card"><Empty icon={page==='transactions'?'swap':page==='customers'?'users':page==='products'?'box':'file'} title={`No ${m.title.toLowerCase()} yet`} text={`Add your first ${m.title.slice(0,-1).toLowerCase()} to start building this workspace.`} action={<button className="btn-primary empty-action" onClick={()=>open(page==='transactions'?'transaction':page.slice(0,-1))}> <Icon name="plus" size={15}/> Add {page==='transactions'?'transaction':page==='customers'?'customer':page==='products'?'product':'invoice'}</button>}/></section>;
 return <section className="records-card"><div className="table-head"><strong>{items.length} record{items.length===1?'':'s'}</strong><span>Stored locally on this device</span></div><div className="table-scroll"><table><thead><tr>{page==='transactions'?<><th>Type</th><th>Description</th><th>Amount</th><th>Date</th><th/></>:page==='customers'?<><th>Customer</th><th>Phone</th><th>Email</th><th/></>:page==='products'?<><th>Item</th><th>Type</th><th>Price</th><th/></>:<><th>Invoice</th><th>Customer</th><th>Amount</th><th>Status</th><th/></>}</tr></thead><tbody>{items.map(x=><tr key={x.id}>{page==='transactions'?<><td><span className={`tag ${x.type}`}>{x.type}</span></td><td><strong>{x.description}</strong></td><td className={x.type==='income'?'positive':'negative'}>{money(x.amount)}</td><td>{new Date(x.createdAt).toLocaleDateString()}</td><td><button className="delete" onClick={()=>remove(m.c,x.id)}>Remove</button></td></>:page==='customers'?<><td><strong>{x.name}</strong></td><td>{x.phone||'—'}</td><td>{x.email||'—'}</td><td><button className="delete" onClick={()=>remove(m.c,x.id)}>Remove</button></td></>:page==='products'?<><td><strong>{x.name}</strong></td><td>{x.type}</td><td>{money(x.price)}</td><td><button className="delete" onClick={()=>remove(m.c,x.id)}>Remove</button></td></>:<><td><strong>{x.number}</strong></td><td>{x.customer}</td><td>{money(x.amount)}</td><td><span className="tag draft">{x.status}</span></td><td><button className="delete" onClick={()=>remove(m.c,x.id)}>Remove</button></td></>}</tr>)}</tbody></table></div></section>}

function Reports({db}){const income=db.transactions.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),expense=db.transactions.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0);return <div className="report"><div className="stats"><Stat label="Income" value={money(income)} note="Recorded"/><Stat label="Expenses" value={money(expense)} note="Recorded"/><Stat label="Net" value={money(income-expense)} note="Income less expenses"/></div><section className="section-card"><div className="card-title"><div><h2>Financial summary</h2><p>Calculated only from transactions you recorded.</p></div></div><div className="report-lines"><div><span>Total income</span><strong>{money(income)}</strong></div><div><span>Total expenses</span><strong>{money(expense)}</strong></div><div className="total"><span>Net position</span><strong>{money(income-expense)}</strong></div></div></section></div>}
function Notifications({db}){return <section className="records-card">{db.notifications.length?<div className="notification-list">{db.notifications.map((n,i)=><div key={i}><Icon name="bell" size={17}/><div><strong>{n.title||'Vero notification'}</strong><p>{n.text}</p><small>{n.date||''}</small></div></div>)}</div>:<Empty icon="bell" title="You're all caught up" text="Vero will place useful system notices here when there is something to tell you."/>}</section>}

function Modal({type,close,submit}){const [f,setF]=useState({});const set=(k,v)=>setF(x=>({...x,[k]:v}));const configs={transaction:{title:'Record transaction',collection:'transactions',label:'Transaction recorded',fields:[['description','Description','What was this for?'],['amount','Amount','KES 0']]},customer:{title:'Add customer',collection:'customers',label:'Customer added',fields:[['name','Name','Customer name'],['phone','Phone','07xx xxx xxx'],['email','Email','customer@example.com']]},product:{title:'Add product or service',collection:'products',label:'Product added',fields:[['name','Name','Product or service'],['type','Type','Product or service'],['price','Price','KES 0']]},invoice:{title:'Create invoice',collection:'invoices',label:'Invoice saved',fields:[['number','Invoice number','INV-001'],['customer','Customer','Customer name'],['amount','Amount','KES 0']]}}[type];const save=e=>{e.preventDefault();if(configs.fields.some(([k])=>!String(f[k]||'').trim()))return;const data={...f};if(type==='transaction')data.type=f.type||'income';if(type==='invoice')data.status='Draft';submit(configs.collection,data,configs.label)};return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={save}><div className="modal-head"><div><small>VERO</small><h2>{configs.title}</h2></div><button type="button" className="close" onClick={close}>×</button></div>{type==='transaction'&&<div className="choice"><button type="button" className={f.type!=='expense'?'chosen':''} onClick={()=>set('type','income')}>Income</button><button type="button" className={f.type==='expense'?'chosen':''} onClick={()=>set('type','expense')}>Expense</button></div>}{configs.fields.map(([k,label,ph])=><Field key={k} label={label}><input value={f[k]||''} onChange={e=>set(k,e.target.value)} placeholder={ph}/></Field>)}<button className="btn-primary" type="submit">Save record</button></form></div>}

export default function VeroApp(){const [loaded,setLoaded]=useState(false);const [user,setUser]=useState(()=>read(AUTH,null));if(!loaded)return <Loader done={()=>setLoaded(true)}/>;if(!user)return <Auth onLogin={u=>{localStorage.setItem(AUTH,JSON.stringify(u));setUser(u)}}/>;return <Shell user={user} onLogout={()=>{localStorage.removeItem(AUTH);setUser(null)}}/>}
